server {
    listen 80;
    server_name services.sabyasachimishra.in;
    root /usr/share/nginx/html;
    index services-landing-page.html;
    location / {
        try_files $uri $uri/ /services-landing-page.html;
    }
}
